### PR TITLE
Fix submit command usage

### LINKED ISSUE #1063: help text for submit
The help text for submit is no longer accurate.
```sh
$ command exercism troubleshoot
...
Current: 3.1.0
...
```
```sh
$ command exercism submit --help
Submit your solution to an Exercism exercise.

    Call the command with the list of files you want to submit.

Usage:
   submit FILE1 [FILE2 ...] [flags]
...
```

The help text still indicates at least one file is required.

(I have an "exercism" shell function: "command" bypasses it)

### PR DESCRIPTION
**Pull request by andrerfcsantos**
Fixes #1063

### CODE REVIEW

**Comment by andrerfcsantos** [comment]
Ready to review.

Just a side note about formatting: CI initially was complaining the code was not formatted with `go fmt`. I found this weird, because my editor runs `go fmt` to format the code. Turns out the problem seems to be that `go1.15 fmt ./...` and `go1.19 fmt ./...` don't agree on the formatting. I had to run `go1.15 fmt ./...` for CI to be happy. This meant `Use: "` having just 1 space between the `:` and `"`. On the other hand, `go1.19 fmt ./...` puts more spaces, in an attempt to align all the values of the struct vertically. I like the `go1.19` formatting more, but used the `go1.15` formatting for CI to pass.

File: cmd/submit.go [hunk 1]
```diff
@@ -19,12 +19,14 @@ import (
...
 var submitCmd = &cobra.Command{
-	Use:     "submit FILE1 [FILE2 ...]",
+	Use: "submit [FILE1	 ...]",
 	Aliases: []string{"s"},
 	Short:   "Submit your solution to an exercise.",
 	Long: `Submit your solution to an Exercism exercise.
 
     Call the command with the list of files you want to submit.
+    If you omit the list of files, the CLI will attempt to submit
+    automatically the appropriate solution files for the exercise.
```
Comment (kotp) [inline cmd/submit.go:29]:
```suggestion
    the appropriate solution files for the exercise.
```

It may not matter if it is automatically, programmatically, or some other way, so I think we can remove that word (and if we do it magically instead later, we will not feel like we have to change this information.)

**Review by kotp — APPROVED** [review]
Non-blocking suggestion for wording.

File: cmd/submit.go [hunk 2]
```diff
@@ -19,12 +19,14 @@ import (
 
 // submitCmd lets people upload a solution to the website.
 var submitCmd = &cobra.Command{
-	Use:     "submit FILE1 [FILE2 ...]",
+	Use: "submit [FILE1	 ...]",
```
Comment (ErikSchierboom) [inline cmd/submit.go:22]: I wonder if we could somehow make this a bit more clear, where previously the text implied multiple files could be submitted. Nested square brackets is weird.

What about:

```suggestion
	Use: "submit [FILE1, ...]",
```
or 
```suggestion
	Use: "submit [FILE(S)]",
```

File: cmd/submit.go (hunk 1 above)
Comment (ErikSchierboom) [reply cmd/submit.go:29]: I agree with this suggestion.

File: cmd/submit.go (hunk 2 above)
Comment (kotp) [reply cmd/submit.go:22]:
```
ls [OPTION]... [FILE]...
```

From the man page for `ls` to indicate optional options and files, as an example of documentation...

Git uses:

```
command [<file> ...]
```

as another example for when a file or files are optionally given, and `less` uses

```
[filename] ...
```

to indicate 0 or more file names.

Comment (ErikSchierboom) [reply cmd/submit.go:22]: Maybe we use the git version?

```suggestion
	Use: "submit [<FILE> ...]",
```

Comment (ErikSchierboom) [reply cmd/submit.go:22]: @andrerfcsantos what do you think about that?

**Comment by kotp** [comment]
Should that merge have been a rebase on main instead of a merge of main into this branch?

File: cmd/submit.go [hunk 3]
```diff
@@ -19,12 +19,14 @@ import (
...
 	Aliases: []string{"s"},
 	Short:   "Submit your solution to an exercise.",
 	Long: `Submit your solution to an Exercism exercise.
 
     Call the command with the list of files you want to submit.
+    If you omit the list of files, the CLI will attempt to submit
+    the appropriate solution files for the exercise.
```
Comment (ErikSchierboom) [inline cmd/submit.go:29]: I think "attempt" sounds odd, like it might fail. Maybe:

```suggestion
    If you omit the list of files, the CLI will submit the
    default solution files for the exercise.
```

Comment (kotp) [reply cmd/submit.go:29]: It might fail, but for various reasons not under its control.  Full disk, lack of network connectivity, DDOS attack on Exercism, etc.  So there are points at which it may attempt to submit and fail.

Maybe if it fails the first time it automatically retries until it succeeds, and so success is guaranteed?
