### PR TITLE
Guard against submitting _spec.* files and READMEs

### LINKED ISSUE #272: Guard against submitting the wrong file
I was moving a little too fast tonight and [accidentally submitted `hamming_spec.lua` instead of `hamming.lua`](http://exercism.io/submissions/7f35bb6eb9684a48ae17583c929f9888). It would be nice if the CLI tool were smart enough to know if the user is accidentally submitting a README or test cases in lieu of a solution.

Would it make sense for the CLI tool to check the filename of the file you're submitting and guard against certain filenames? We could check for things like: 

- anything containing "README"
- (name of the exercise) + "_spec.lua"
- (name of the exercise) + "_test.clj"

### PR DESCRIPTION
**Pull request by daveyarwood**
Closes #272.

I see that we allow users to submit test files if they include a `--test` flag (#189) -- should we do the same to allow submitting READMEs? If so, I propose we change the `--test` flag to a `--force` flag and let it apply to READMEs and any other files we may want to complain about in the future.

### CODE REVIEW

**Comment by Tonkpils** [comment]
Nope, I don't think we ever want to allow submitting the README. This looks great :)

File: cmd/cmd.go [hunk 1]
```diff
@@ -17,8 +18,12 @@ func isTest(path string) bool {
 
 	file := filepath.Base(path)
 	name := file[:len(file)-len(ext)]
-	if name == "test" {
+	if name == "test" || name == "spec" {
```
Comment (kytrinyx) [inline cmd/cmd.go]: perl doesn't have test or spec in the name, for what it's worth. Languages that have a different pattern for the test files have this defined in the language config, so we could expose it via the API (and perhaps write it to a dotfile somewhere that we can load and check.

Comment (daveyarwood) [inline cmd/cmd.go]: I like that idea, seems much safer.

**Comment by kytrinyx** [comment]
OK cool, I'll add an issue for it.

**Comment by kytrinyx** [comment]
https://github.com/exercism/x-api/issues/95
