### PR TITLE
[nextercism] Implement troubleshoot command.

### LINKED ISSUE #415: nextercism: implement troubleshoot command
_To be merged into the nextercism branch in https://github.com/exercism/cli/pull/410_

Command name: `troubleshoot` (alias `t`).
File: `cmd/troubleshoot.go`.

I chose the name `troubleshoot` rather than `debug` so that we can have a single-letter alias without crashing into the `download` command.

The current implementation (https://github.com/exercism/cli/blob/master/cmd/debug.go) is probably almost directly portable. The only difference would be that you can get a user configuration with `config.NewUserConfig()` instead of making one from scratch and populating it.

**UPDATE** There is a second difference. We'll have an explicit `/ping` endpoint to call for the Exercism API.

### PR DESCRIPTION
**Pull request by robphoenix**
Closes #415

### CODE REVIEW

**Comment by robphoenix** [comment]
I've not included tests. I wondered if any tests should be against `status.go` rather than parsing the output from the troubleshoot command. If there are tests that should be here let me know and I'll write them up.

Example output for reference:

```shell
gopath/src/github.com/exercism/cli [troubleshoot ≡] ◯ 
> go run exercism/main.go troubleshoot     


Troubleshooting Information
===========================

Version
----------------
Current: 3.0.0-alpha.1
Latest:  2.4.1


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/rob
Workspace: /home/rob/Dropbox/code/exercism
Config:    /home/rob/.config/exercism/user.json
API key:   6a99*************************bb0

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 159.922897ms

Exercism:
    * http://exercism.io/api/v1
    * [connected]
    * 495.754551ms

X-API:
    * http://x.exercism.io/ping
    * [connected]
    * 398.858616ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.



```

**Comment by kytrinyx** [comment]
> I wondered if any tests should be against status.go rather than parsing the output from the troubleshoot command.

Yeah, I completely agree. Doing an example test of the troubleshoot output or whatever is messy and gross. I actually tried doing it when I extracted the debug stuff into the `cli` package and... gave up.

File: cli/status.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func newAPIReachabilityStatus() apiReachabilityStatus {
 		Services: []*apiPing{
 			{Service: "GitHub", URL: "https://api.github.com"},
 			{Service: "Exercism", URL: "http://exercism.io/api/v1"},
-			{Service: "X-API", URL: "http://x.exercism.io"},
+			{Service: "X-API", URL: "http://x.exercism.io/ping"},
```
Comment (kytrinyx) [inline cli/status.go]: I just realized—we're going to be killing off the x-api (yay).

So we will only have one exercism API to test against. The URL is `https://api.exercism.io/v1/ping` right now. I don't know how much of the `config.APIConfig` is present in the codebase at the moment, but we can rework this to use load up that config, which has the `BaseURL` (which I think is https://api.exercism.io/v1 right now), and we can add a `ping` endpoint to the default endpoints.

File: config/api_config.go [hunk 2]
```diff
@@ -8,10 +8,11 @@ import (
 )
 
 var (
-	defaultBaseURL   = "https://api.exercism.com/v1"
```
Comment (robphoenix) [inline config/api_config.go]: this is a mistake, right?

File: config/api_config.go [hunk 3]
```diff
@@ -78,3 +78,8 @@ func (cfg *APIConfig) Load(v *viper.Viper) error {
 	cfg.readIn(v)
 	return v.Unmarshal(&cfg)
 }
+
+// APIEndpoint returns the full URL for a given endpoint
+func APIEndpoint(endpoint string) string {
```
Comment (robphoenix) [inline config/api_config.go]: I wanted to be able to use the "ping" default endpoint without having to create a new API config and dealt with the error. Let me know if this is the wrong way to go about this.

**Comment by robphoenix** [comment]
> maybe a test for Censor to start since its a flag in troubleshoot?

good idea, added.

File: config/api_config.go (hunk 2 above)
Comment (kytrinyx) [inline config/api_config.go]: Indeed. That should be fixed in the nextercism branch.

File: config/api_config.go (hunk 3 above)
Comment (kytrinyx) [inline config/api_config.go]: This will work as long as people are not trying to test something locally. If they've overridden the base url in their local config to work against a development server, this won't pick it up.

Comment (robphoenix) [inline config/api_config.go]: You're right, I've taken this out, and used `NewAPIConfig()`. Is the error propagation alright?

Comment (kytrinyx) [inline config/api_config.go]: >  Is the error propagation alright?

I'm not following. Would you elaborate?

Comment (kytrinyx) [inline config/api_config.go]: Oh, wait. You mean the err from the NewAPIConfig()? I think that looks fine. It really shouldn't error out under normal circumstances (I guess that goes for most things, but still. Some errors are fairly expected, whereas this is going to be a very rare occurrence).

Comment (robphoenix) [inline config/api_config.go]: Yeah I figured that would be the case, but I thought I'd best be safe than sorry.

File: cli/status.go [hunk 4]
```diff
@@ -85,12 +89,15 @@ func (status *Status) compile() (string, error) {
...
+	apiCfg, err := config.NewAPIConfig()
+	if err != nil {
+		return apiReachabilityStatus{}, nil
+	}
 	ar := apiReachabilityStatus{
 		Services: []*apiPing{
 			{Service: "GitHub", URL: "https://api.github.com"},
-			{Service: "Exercism", URL: "http://exercism.io/api/v1"},
-			{Service: "X-API", URL: "http://x.exercism.io"},
+			{Service: "Exercism", URL: apiCfg.BaseURL + apiCfg.Endpoints["ping"]},
```
Comment (kytrinyx) [inline cli/status.go]: I think this could be `apiCfg.URL("ping")`. It basically does exactly this, so I'm not sure it's an improvement :)

Comment (kytrinyx) [inline cli/status.go]: I improved the URL() function in #451

Comment (robphoenix) [inline cli/status.go]: I think I actually used `URL("ping")` initially, but removed it to avoid creating the error from `NewAPIConfig()` and then completely forgot it existed when I changed it to what it is now. Brain like a sieve. Or as my son keeps saying *My brain forgot to tell me*.

Comment (kytrinyx) [inline cli/status.go]: > My brain forgot to tell me.

That is lovely. My brain does that all the time.
