### PR TITLE
Error message returned if the track is locked

### LINKED ISSUE #870: Exercism 3.0.12 no longer reports errors when trying to download a locked exercise
Steps to reproduce:

1. Try to download an exercise that you have not yet unlocked
2. Notice the output "Downloaded to (exercism-workspace-dir)/users"
3. Check the users directory as well as the track directory and notice no folders have been downloaded

This was working properly before the recent update.

### PR DESCRIPTION
**Pull request by Jrank2013**
This fixes #870.

If the user has not unlocked the track that they have requested to download, the cli will return an error.

### CODE REVIEW

File: cmd/download.go [hunk 1]
```diff
@@ -188,6 +188,9 @@ func newDownload(flags *pflag.FlagSet, usrCfg *viper.Viper) (*download, error) {
 	if err := json.NewDecoder(res.Body).Decode(&d.payload); err != nil {
 		return nil, decodedAPIError(res)
 	}
+	if d.payload.Error.Message != "" {
+		return nil, errors.New(d.payload.Error.Message)
+	}
```
Comment (kytrinyx) [inline cmd/download.go]: On looking at this I'm wondering why the `decodedAPIError` above doesn't return the error. It seems like it should, right?

https://github.com/exercism/cli/blob/4ad01b1562f320ac6c75b9463827b5d5857f4f03/cmd/cmd.go#L98

Comment (Jrank2013) [reply cmd/download.go]: You were right. There wasn't a check for the http status code which was causing the issue

File: cmd/download.go [hunk 2]
```diff
@@ -185,7 +187,10 @@ func newDownload(flags *pflag.FlagSet, usrCfg *viper.Viper) (*download, error) {
 	}
 	defer res.Body.Close()
 
-	if err := json.NewDecoder(res.Body).Decode(&d.payload); err != nil {
+	body, err := ioutil.ReadAll(res.Body)
+	res.Body = ioutil.NopCloser(bytes.NewReader(body))
+
+	if err := json.Unmarshal(body, &d.payload); err != nil || res.StatusCode < 200 || res.StatusCode > 299 {
```
Comment (kytrinyx) [inline cmd/download.go]: The `decodedAPIError` already unmarshals the error, right? Can we move all the error handling logic into that method?

File: cmd/download_test.go [hunk 3]
```diff
@@ -272,6 +272,42 @@ func assertDownloadedCorrectFiles(t *testing.T, targetDir string) {
 	assert.True(t, os.IsNotExist(err), "It should not write the file if empty.")
 }
 
+func TestDownloadError(t *testing.T) {
```
Comment (kytrinyx) [inline cmd/download_test.go]: 😍 Thank you!

File: cmd/download_test.go [hunk 4]
```diff
@@ -272,6 +272,42 @@ func assertDownloadedCorrectFiles(t *testing.T, targetDir string) {
...
+		DefaultBaseURL:  "http://example.com",
+	}
+
+	flags := pflag.NewFlagSet("fake", pflag.PanicOnError)
+	setupDownloadFlags(flags)
+	flags.Set("uuid", "value")
+
+	err = runDownload(cfg, flags, []string{})
+
+	fmt.Println(err)
```
Comment (kytrinyx) [inline cmd/download_test.go]: Would you mind removing the debugging output here?

File: cmd/download_test.go [hunk 5]
```diff
@@ -272,6 +272,42 @@ func assertDownloadedCorrectFiles(t *testing.T, targetDir string) {
...
+
+	assert.Regexp(t, "test error", err.Error())
```
Comment (kytrinyx) [inline cmd/download_test.go]: Does this need to be a regexp? The error string should be just "test error", right?

File: cmd/download.go (hunk 2 above)
Comment (Jrank2013) [reply cmd/download.go]: The response body can only be read once. If we unmarshal or decode the body before saving a copy we wouldn't have a way to decode the JSON into the error struct.

File: cmd/download.go [hunk 6]
```diff
@@ -185,7 +187,14 @@ func newDownload(flags *pflag.FlagSet, usrCfg *viper.Viper) (*download, error) {
 	}
 	defer res.Body.Close()
 
-	if err := json.NewDecoder(res.Body).Decode(&d.payload); err != nil {
+	if res.StatusCode < 200 || res.StatusCode > 299 {
+		return nil, decodedAPIError(res)
```
Comment (kytrinyx) [inline cmd/download.go]: Now we have the `decodedAPIError` twice, which seems like it shouldn't be necessary.

I'm sorry if I'm being dumb, here. I'll take some time after work to pull this down and play around with it to see if I understand it better.

Comment (kytrinyx) [reply cmd/download.go]: Ok, I played with this and I totally see what's going on.

Sorry for being slow!

Comment (Jrank2013) [reply cmd/download.go]: No problem, just glad I can help!
